version: "3.1"
services:
  redis:
    image: redis:latest

  app:
    build: .
    links:
      - redis
    command: ["npm", "start"]
    ports: ["3000:3000"]
    environment:
      # PERSONAL_OAUTH_TOKEN_FILE: /run/secrets/personal_oauth_file
      PRODUCTION: "false"
      PORT: 3000
#     secrets:
#       - personal_oauth_file

# secrets:
#   personal_oauth_file:
#     file: personal_oauth.txt
