version: "3.1"
services:
  app:
    build: .
    command: ["npm", "start"]
    ports: ["3000:3000"]
    environment:
      PRODUCTION: "false"
      PORT: 3000
    secrets:
      - MAIL_API_KEY
      - AUDIENCE_ID

secrets:
  MAIL_API_KEY:
    file: ./config/MAIL_API_KEY
  AUDIENCE_ID:
    file: ./config/AUDIENCE_ID
